### ISSUE TITLE
请问README里面的彩色二维码是怎么做到那么清晰的

### ISSUE THREAD

**Issue by cloud26** [chinuno-usami/CuteR#8]
我直接运行 `cuter -p sample_input.png -C test  -o my_sample_output.jpg`得到的图片是这样的
![my_sample_output](https://user-images.githubusercontent.com/5143017/37202048-671b85a8-23c4-11e8-825a-abd240ded6bf.jpg)

**Comment by chinuno-usami** [comment]
你这是很早之前的版本了吧。现在默认就是我readme那样的

2018年3月9日 下午6:20，"cloud26" <notifications@github.com>寫道：

我直接运行 cuter -p sample_input.png -C test -o my_sample_output.jpg得到的图片是这样的
[image: my_sample_output]
<https://user-images.githubusercontent.com/5143017/37202048-671b85a8-23c4-11e8-825a-abd240ded6bf.jpg>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/chinuno-usami/CuteR/issues/8>, or mute the thread

**Comment by cloud26** [comment]
不是诶，之前用的是PyPi上面的版本，刚刚我直接用git上面最新的代码尝试了一下，输出是非高清的图。有啥特殊的参数么？

**Comment by cloud26** [comment]
抱歉，我多加了一个`-p`，没太细看文档，想当然地以为是图片参数了。谢谢！

**Comment by chinuno-usami** [comment]
哈哈原来是这样。我也都没仔细看
